name: professional_muslim
description: A professional Muslim application for Azkar and more.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  path_provider: ^2.1.0
  flutter_local_notifications: ^15.1.0+1
  url_launcher: ^6.1.12
  audioplayers: ^5.1.0
  geolocator: ^10.0.0
  adhan: ^2.0.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/data/quran_data.json
    - assets/images/
    - assets/audio/
  # fonts:
  #   - family: Amiri
  #     fonts:
  #       - asset: assets/fonts/Amiri-Regular.ttf
  #       - asset: assets/fonts/Amiri-Bold.ttf
  #         weight: 700
